web:
  # image: daocloud.io/yeting/craft-docker:master-23932a7
  build: .
  ports:
    - 8080:80
  links:
    - mysql
  # env vars are replace into /cms/craft/config
  environment:
    # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
    # LANG: C.UTF-8

    # Make available by coalition
    # VIRTUAL_HOST: craft.dev
    # VIRTUAL_PORT: 80

    # DB is linked
    CRAFT_DB_SERVER: mysql
    CRAFT_DB_NAME: craft_dev
    CRAFT_DB_PORT: 3306
    CRAFT_DB_USER: craft_dev
    CRAFT_DB_PASSWORD: secret

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: craft_dev
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: craft_dev
  volumes:
    # Persistent data baby
    - /var/lib/mysql
